<?php

if(!$this->getParentBlock()->getOrder() || !$this->getParentBlock()->getSlip())
{
	return;
}

$dadosboleto = $this->getSlipData();

$codigobanco = "341";
$codigo_banco_com_dv = geraCodigoBanco($codigobanco);
$nummoeda = "9";
$fator_vencimento = fator_vencimento($dadosboleto["data_vencimento"]);

//valor tem 10 digitos, sem virgula
$valor = formata_numero($dadosboleto["valor_boleto"],10,0,"valor");
//agencia é 4 digitos
$agencia = formata_numero($dadosboleto["agencia"],4,0);
//conta é 5 digitos + 1 do dv
$conta = formata_numero($dadosboleto["conta"],5,0);
$conta_dv = formata_numero($dadosboleto["conta_dv"],1,0);
//carteira 175
$carteira = $dadosboleto["carteira"];
//nosso_numero no maximo 8 digitos
$nnum = formata_numero($dadosboleto["nosso_numero"],8,0);

$codigo_barras = $codigobanco.$nummoeda.$fator_vencimento.$valor.$carteira.$nnum.modulo_10($agencia.$conta.$carteira.$nnum).$agencia.$conta.modulo_10($agencia.$conta).'000';
// 43 numeros para o calculo do digito verificador
$dv = digitoVerificador_barra($codigo_barras);
// Numero para o codigo de barras com 44 digitos
$linha = substr($codigo_barras,0,4).$dv.substr($codigo_barras,4,43);

$nossonumero = $carteira.'/'.$nnum.'-'.modulo_10($agencia.$conta.$carteira.$nnum);
$agencia_codigo = $agencia." / ". $conta."-".modulo_10($agencia.$conta);

$dadosboleto["codigo_barras"] = $linha;
$dadosboleto["linha_digitavel"] = monta_linha_digitavel($linha); // verificar
$dadosboleto["agencia_codigo"] = $agencia_codigo ;
$dadosboleto["nosso_numero"] = $nossonumero;
$dadosboleto["codigo_banco_com_dv"] = $codigo_banco_com_dv;


// FUNÇÕES
// Algumas foram retiradas do Projeto PhpBoleto e modificadas para atender as particularidades de cada banco

function digitoVerificador_barra($numero) {
	$resto2 = modulo_11($numero, 9, 1);
	$digito = 11 - $resto2;
     if ($digito == 0 || $digito == 1 || $digito == 10  || $digito == 11) {
        $dv = 1;
     } else {
        $dv = $digito;
     }
	 return $dv;
}

function formata_numero($numero,$loop,$insert,$tipo = "geral") {
	if ($tipo == "geral") {
		$numero = str_replace(",","",$numero);
		while(strlen($numero)<$loop){
			$numero = $insert . $numero;
		}
	}
	if ($tipo == "valor") {
		/*
		retira as virgulas
		formata o numero
		preenche com zeros
		*/
		$numero = str_replace(",","",$numero);
		while(strlen($numero)<$loop){
			$numero = $insert . $numero;
		}
	}
	if ($tipo == "convenio") {
		while(strlen($numero)<$loop){
			$numero = $numero . $insert;
		}
	}
	return $numero;
}


function fbarcode($valor){

$fino = 1 ;
$largo = 3 ;
$altura = 50 ;

  $barcodes[0] = "00110" ;
  $barcodes[1] = "10001" ;
  $barcodes[2] = "01001" ;
  $barcodes[3] = "11000" ;
  $barcodes[4] = "00101" ;
  $barcodes[5] = "10100" ;
  $barcodes[6] = "01100" ;
  $barcodes[7] = "00011" ;
  $barcodes[8] = "10010" ;
  $barcodes[9] = "01010" ;
  for($f1=9;$f1>=0;$f1--){ 
    for($f2=9;$f2>=0;$f2--){  
      $f = ($f1 * 10) + $f2 ;
      $texto = "" ;
      for($i=1;$i<6;$i++){ 
        $texto .=  substr($barcodes[$f1],($i-1),1) . substr($barcodes[$f2],($i-1),1);
      }
      $barcodes[$f] = $texto;
    }
  }


//Desenho da barra


//Guarda inicial
?><img src=<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/p.png width=<?php echo $fino?> height=<?php echo $altura?> border=0><img 
src=<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/b.png width=<?php echo $fino?> height=<?php echo $altura?> border=0><img 
src=<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/p.png width=<?php echo $fino?> height=<?php echo $altura?> border=0><img 
src=<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/b.png width=<?php echo $fino?> height=<?php echo $altura?> border=0><img 
<?php
$texto = $valor ;
if((strlen($texto) % 2) <> 0){
	$texto = "0" . $texto;
}

// Draw dos dados
while (strlen($texto) > 0) {
  $i = round(esquerda($texto,2));
  $texto = direita($texto,strlen($texto)-2);
  $f = $barcodes[$i];
  for($i=1;$i<11;$i+=2){
    if (substr($f,($i-1),1) == "0") {
      $f1 = $fino ;
    }else{
      $f1 = $largo ;
    }
?>
    src=<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/p.png width=<?php echo $f1?> height=<?php echo $altura?> border=0><img 
<?php
    if (substr($f,$i,1) == "0") {
      $f2 = $fino ;
    }else{
      $f2 = $largo ;
    }
?>
    src=<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/b.png width=<?php echo $f2?> height=<?php echo $altura?> border=0><img 
<?php
  }
}

// Draw guarda final
?>
src=<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/p.png width=<?php echo $largo?> height=<?php echo $altura?> border=0><img 
src=<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/b.png width=<?php echo $fino?> height=<?php echo $altura?> border=0><img 
src=<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/p.png width=<?php echo 1?> height=<?php echo $altura?> border=0> 
  <?php
} //Fim da função

function esquerda($entra,$comp){
	return substr($entra,0,$comp);
}

function direita($entra,$comp){
	return substr($entra,strlen($entra)-$comp,$comp);
}

function fator_vencimento($data) {
	$data = explode("/",$data);
	$ano = $data[2];
	$mes = $data[1];
	$dia = $data[0];
    return(abs((_dateToDays("1997","10","07")) - (_dateToDays($ano, $mes, $dia))));
}

function _dateToDays($year,$month,$day) {
    $century = substr($year, 0, 2);
    $year = substr($year, 2, 2);
    if ($month > 2) {
        $month -= 3;
    } else {
        $month += 9;
        if ($year) {
            $year--;
        } else {
            $year = 99;
            $century --;
        }
    }
    return ( floor((  146097 * $century)    /  4 ) +
            floor(( 1461 * $year)        /  4 ) +
            floor(( 153 * $month +  2) /  5 ) +
                $day +  1721119);
}

function modulo_10($num) { 
		$numtotal10 = 0;
        $fator = 2;

        // Separacao dos numeros
        for ($i = strlen($num); $i > 0; $i--) {
            // pega cada numero isoladamente
            $numeros[$i] = substr($num,$i-1,1);
            // Efetua multiplicacao do numero pelo (falor 10)
            // 2002-07-07 01:33:34 Macete para adequar ao Mod10 do Itaú
            $temp = $numeros[$i] * $fator; 
            $temp0=0;
            foreach (preg_split('//',$temp,-1,PREG_SPLIT_NO_EMPTY) as $k=>$v){ $temp0+=$v; }
            $parcial10[$i] = $temp0; //$numeros[$i] * $fator;
            // monta sequencia para soma dos digitos no (modulo 10)
            $numtotal10 += $parcial10[$i];
            if ($fator == 2) {
                $fator = 1;
            } else {
                $fator = 2; // intercala fator de multiplicacao (modulo 10)
            }
        }
		
        // várias linhas removidas, vide função original
        // Calculo do modulo 10
        $resto = $numtotal10 % 10;
        $digito = 10 - $resto;
        if ($resto == 0) {
            $digito = 0;
        }
		
        return $digito;
		
}

function modulo_11($num, $base=9, $r=0)  {
    /**
     *   Autor:
     *           Pablo Costa <pablo@users.sourceforge.net>
     *
     *   Função:
     *    Calculo do Modulo 11 para geracao do digito verificador 
     *    de boletos bancarios conforme documentos obtidos 
     *    da Febraban - www.febraban.org.br 
     *
     *   Entrada:
     *     $num: string numérica para a qual se deseja calcularo digito verificador;
     *     $base: valor maximo de multiplicacao [2-$base]
     *     $r: quando especificado um devolve somente o resto
     *
     *   Saída:
     *     Retorna o Digito verificador.
     *
     *   Observações:
     *     - Script desenvolvido sem nenhum reaproveitamento de código pré existente.
     *     - Assume-se que a verificação do formato das variáveis de entrada é feita antes da execução deste script.
     */                                        

    $soma = 0;
    $fator = 2;

    /* Separacao dos numeros */
    for ($i = strlen($num); $i > 0; $i--) {
        // pega cada numero isoladamente
        $numeros[$i] = substr($num,$i-1,1);
        // Efetua multiplicacao do numero pelo falor
        $parcial[$i] = $numeros[$i] * $fator;
        // Soma dos digitos
        $soma += $parcial[$i];
        if ($fator == $base) {
            // restaura fator de multiplicacao para 2 
            $fator = 1;
        }
        $fator++;
    }

    /* Calculo do modulo 11 */
    if ($r == 0) {
        $soma *= 10;
        $digito = $soma % 11;
        if ($digito == 10) {
            $digito = 0;
        }
        return $digito;
    } elseif ($r == 1){
        $resto = $soma % 11;
        return $resto;
    }
}

// Alterada por Glauber Portella para especificação do Itaú
function monta_linha_digitavel($codigo) {
		// campo 1
        $banco    = substr($codigo,0,3);
        $moeda    = substr($codigo,3,1);
        $ccc      = substr($codigo,19,3);
		$ddnnum   = substr($codigo,22,2);
		$dv1      = modulo_10($banco.$moeda.$ccc.$ddnnum);
		// campo 2
		$resnnum  = substr($codigo,24,6);
		$dac1     = substr($codigo,30,1);//modulo_10($agencia.$conta.$carteira.$nnum);
		$dddag    = substr($codigo,31,3);
		$dv2      = modulo_10($resnnum.$dac1.$dddag);
		// campo 3
		$resag    = substr($codigo,34,1);
		$contadac = substr($codigo,35,6); //substr($codigo,35,5).modulo_10(substr($codigo,35,5));
		$zeros    = substr($codigo,41,3);
		$dv3      = modulo_10($resag.$contadac.$zeros);
		// campo 4
		$dv4      = substr($codigo,4,1);
		// campo 5
        $fator    = substr($codigo,5,4);
        $valor    = substr($codigo,9,10);
		
        $campo1 = substr($banco.$moeda.$ccc.$ddnnum.$dv1,0,5) . '.' . substr($banco.$moeda.$ccc.$ddnnum.$dv1,5,5);
        $campo2 = substr($resnnum.$dac1.$dddag.$dv2,0,5) . '.' . substr($resnnum.$dac1.$dddag.$dv2,5,6);
        $campo3 = substr($resag.$contadac.$zeros.$dv3,0,5) . '.' . substr($resag.$contadac.$zeros.$dv3,5,6);
        $campo4 = $dv4;
        $campo5 = $fator.$valor;
		
        return "$campo1 $campo2 $campo3 $campo4 $campo5"; 
}

function geraCodigoBanco($numero) {
    $parte1 = substr($numero, 0, 3);
    $parte2 = modulo_11($parte1);
    return $parte1 . "-" . $parte2;
}

?>

<style type="text/css">
	.cp {  font: bold 10px Arial; color: black}
	.ti {  font: 9px Arial, Helvetica, sans-serif}
	.ld { font: bold 15px Arial; color: #000000}
	.ct { font: 9px "Arial Narrow"; color: #000033}
	.cn { font: 9px Arial; color: black }
	.bc { font: bold 20px Arial; color: #000000 }
	.ld2 { font: bold 12px Arial; color: #000000 }
	
	
	/* textos e imagens */
	.instructions
	{
		font: bold 10px Arial;
		color: #000000;
	}
	
	.header-bar-code-number
	{
		font: bold 12px Arial;
		color: #000000;
	}
	
	.company-logo
	{
		height: 45px;
	}
	
	.bank-logo
	{
		width: 150px;
		height: 37px;
		display: block;
	}
	
	.company-info
	{
		font-size: 9px;
		font-family: Arial, Helvetica, 'sans-serif';
	}
	
	.large-font
	{
		font: bold 20px Arial;
		color: #000000;
	}
	
	.medium-font
	{
		font: bold 15px Arial;
		color: #000000;
	}
	
	.small-font
	{
		font: bold 10px Arial;
		color: #000000;
	}
	
	.tiny-font
	{
		font: 9px "Arial Narrow";
		color: #000033;
	}
	
	/* estrutura */
	.container-row
	{
		width: 666px;
	}
	
	.cutting-line
	{
		width: 665px;
		height: 1px;
		display: block;
	}
	
	.solid-line
	{
		width: 666px;
		height: 2px;
		display: block;
	}
	
	.thin-solid-line
	{
		width: 666px;
		height: 1px;
		display: block;
	}
	
	.container-company-logo
	{
		float: left;
		margin-left: 20px;
		margin-right: 20px;
	}
	
	.large-vertical-separator
	{
		width: 2px;
		height: 22px;
		background-image: url('<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/3.png');
	}
	
	.small-vertical-separator
	{
		width: 1px;
		height: 13px;
		margin-right: 7px;
		display: block;
	}
	
</style>

<!-- cabecalho com instrucoes de impressao do documento -->
<div class="container-row instructions" style="text-align: center;">
	<span>Instruções de Impressão</span>
</div>

<div class="container-row instructions">
	<ul style="margin: 0;">
		<li>Imprima em impressora jato de tinta (ink jet) ou laser em qualidade normal ou alta (Não use modo econômico).</li>
		<li>Utilize folha A4 (210 x 297 mm) ou Carta (216 x 279 mm) e margens mínimas à esquerda e à direita do formulário.</li>
		<li>Corte na linha indicada. Não rasure, risque, fure ou dobre a região onde se encontra o código de barras.</li>
		<li>Caso não apareça o código de barras no final, clique em F5 para atualizar esta tela.</li>
		<li>Caso tenha problemas ao imprimir, copie a seqüencia numérica abaixo e pague no caixa eletrônico ou no internet banking:</li>
	</ul>
	<br />
	<div class="header-bar-code-number" style="margin-left: 28px;">
		Linha Digitável: &nbsp;<?php echo $dadosboleto["linha_digitavel"]; ?>
	</div>
	<div class="header-bar-code-number" style="margin-left: 28px;">
		Valor: &nbsp;&nbsp;R$ <?php echo $dadosboleto["valor_boleto"]; ?>
	</div>
</div>

<!-- separacao com marcacao para recorte -->
<div class="container-row" style="margin: 15px 0 15px 0;">
	<img alt="" class="cutting-line" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/6.png" />
	<div class="instructions" style="width: 665px; text-align: right;"> Recido do Sacado</div>
</div>

<!-- logomarca e informacoes da empresa -->
<div class="container-row">
	<div class="container-company-logo">
		<img class="company-logo" src="<?php echo $this->getSkinUrl('images/logo.png'); ?>" />
	</div>
	<div class="company-info">
		<?php echo $dadosboleto["identificacao"];  ?><br />
		<?php echo isset($dadosboleto["cpf_cnpj"]) ? $dadosboleto["cpf_cnpj"] . "<br />" : ''; ?>
		<?php echo $dadosboleto["endereco"]; ?><br />
		<?php echo $dadosboleto["cidade_uf"]; ?><br />
	</div>
</div>

<br />

<!-- primeiro quadro -->
<table class="container-row" cellpadding="0" cellspacing="0" border="0">
	<tbody>
		<tr>
			<td valign="bottom">
				<img class="bank-logo" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/itau.png" />
			</td>
			<td valign="bottom" align="left">
				<div class="large-vertical-separator"></div>
			</td>
			<td valign="bottom" align="center">
				<div class="large-font" style="">
					<?php echo $dadosboleto["codigo_banco_com_dv"]; ?>
				</div>
			</td>
			<td valign="bottom" align="left">
				<div class="large-vertical-separator"></div>
			</td>
			<td valign="bottom" align="right">
				<div class="medium-font" style="margin-bottom: 4px;">
					<?php echo $dadosboleto["linha_digitavel"]; ?>
				</div>
			</td>
		</tr>
	</tbody>
</table>

<div class="container-row" style="margin-top: 3px;">
	<img alt="" class="solid-line" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
</div>

<table class="container-row" cellpadding="0" cellspacing="0" border="0">
	<tbody>
		<tr class="tiny-font">
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left">
				Cedente
			</td>
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left">
				Agência / Código do Cedente
			</td>
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left">
				Espécie
			</td>
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left" style="width: 53px;">
				Quantidade
			</td>
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left" style="width: 120px;">
				Nosso Número
			</td>
		</tr>
		<tr class="small-font">
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left">
				<?php echo $dadosboleto["cedente"]; ?>
			</td>
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left">
				<?php echo $dadosboleto["agencia_codigo"]; ?>
			</td>
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left">
				<?php echo $dadosboleto["especie"]; ?>
			</td>
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left">
				<?php echo $dadosboleto["quantidade"]; ?>
			</td>
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="right">
				<?php echo $dadosboleto["nosso_numero"]; ?>
			</td>
		</tr>
	</tbody>
</table>

<div class="container-row">
	<img alt="" class="thin-solid-line" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/2.png" />
</div>

<table class="container-row" cellpadding="0" cellspacing="0" border="0">
	<tbody>
		<tr class="tiny-font">
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left">
				Número do Documento
			</td>
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left">
				CPF/CNPJ
			</td>
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left">
				Vencimento
			</td>
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left" style="width: 181px;">
				Valor Documento
			</td>
		</tr>
		<tr class="small-font">
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left">
				<?php echo $dadosboleto["numero_documento"]; ?>
			</td>
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left">
				<?php echo $dadosboleto["cpf_cnpj"]; ?>
			</td>
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left">
				<?php echo $dadosboleto["data_vencimento"]; ?>
			</td>
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="right">
				<?php echo $dadosboleto["valor_boleto"]; ?>
			</td>
		</tr>
	</tbody>
</table>

<div class="container-row">
	<img alt="" class="thin-solid-line" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/2.png" />
</div>

<table class="container-row" cellpadding="0" cellspacing="0" border="0">
	<tbody>
		<tr class="tiny-font">
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left">
				(-) Desconto / Abatimentos
			</td>
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left">
				(-) Outras deduções
			</td>
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left">
				(+) Mora / Multa
			</td>
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left">
				(+) Outros acréscimos
			</td>
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left" style="width: 181px;">
				(=) Valor cobrado
			</td>
		</tr>
		<tr class="small-font">
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left">
				
			</td>
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left">
				
			</td>
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left">
				
			</td>
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left">
				
			</td>
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left">
				
			</td>
		</tr>
	</tbody>
</table>

<div class="container-row">
	<img alt="" class="thin-solid-line" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/2.png" />
</div>

<table class="container-row" cellpadding="0" cellspacing="0" border="0">
	<tbody>
		<tr class="tiny-font">
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left">
				Sacado
			</td>
		</tr>
		<tr class="small-font">
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left">
				<?php echo $dadosboleto["sacado"]; ?>
			</td>
		</tr>
	</tbody>
</table>

<div class="container-row">
	<img alt="" class="thin-solid-line" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/2.png" />
</div>

<table class="container-row" cellpadding="0" cellspacing="0" border="0">
	<tbody>
		<tr class="tiny-font">
			<td valign="top" align="left" style="width: 8px;">
				
			</td>
			<td valign="top" align="left">
				Demonstrativo
			</td>
			<td valign="top" align="right">
				Autenticação Mecânica
			</td>
		</tr>
		<tr class="small-font">
			<td valign="top" align="left" style="width: 8px;">
				
			</td>
			<td valign="top" align="left">
				<br />
				<?php echo $dadosboleto["demonstrativo1"]; ?><br />
				<?php echo $dadosboleto["demonstrativo2"]; ?><br />
			</td>
		</tr>
	</tbody>
</table>
<br />
<div class="container-row tiny-font" style="text-align: right;">
	Corte na linha pontilhada
</div>
<div class="container-row">
	<img alt="" class="cutting-line" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/6.png" />
</div>
<br />

<!-- segundo quadro -->
<table class="container-row" cellpadding="0" cellspacing="0" border="0">
	<tbody>
		<tr>
			<td valign="bottom">
				<img class="bank-logo" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/itau.png" />
			</td>
			<td valign="bottom" align="left">
				<div class="large-vertical-separator"></div>
			</td>
			<td valign="bottom" align="center">
				<div class="large-font" style="">
					<?php echo $dadosboleto["codigo_banco_com_dv"]; ?>
				</div>
			</td>
			<td valign="bottom" align="left">
				<div class="large-vertical-separator"></div>
			</td>
			<td valign="bottom" align="right">
				<div class="medium-font" style="margin-bottom: 4px;">
					<?php echo $dadosboleto["linha_digitavel"]; ?>
				</div>
			</td>
		</tr>
	</tbody>
</table>

<div class="container-row" style="margin-top: 3px;">
	<img alt="" class="solid-line" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
</div>

<table class="container-row" cellpadding="0" cellspacing="0" border="0">
	<tbody>
		<tr class="tiny-font">
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left">
				Local de Pagamento
			</td>
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left" style="width: 181px;">
				Vencimento
			</td>
		</tr>
		<tr class="small-font">
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left">
				Pagável em qualquer Banco até o vencimento
			</td>
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="right">
				<?php echo $dadosboleto["data_vencimento"]; ?>
			</td>
		</tr>
	</tbody>
</table>

<div class="container-row">
	<img alt="" class="thin-solid-line" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/2.png" />
</div>

<table class="container-row" cellpadding="0" cellspacing="0" border="0">
	<tbody>
		<tr class="tiny-font">
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left">
				Cedente
			</td>
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left" style="width: 181px;">
				Agência / Código cedente
			</td>
		</tr>
		<tr class="small-font">
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left">
				<?php echo $dadosboleto["cedente"]; ?>
			</td>
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="right">
				<?php echo $dadosboleto["agencia_codigo"]; ?>
			</td>
		</tr>
	</tbody>
</table>

<div class="container-row">
	<img alt="" class="thin-solid-line" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/2.png" />
</div>

<table class="container-row" cellpadding="0" cellspacing="0" border="0">
	<tbody>
		<tr class="tiny-font">
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left">
				Data do documento
			</td>
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left">
				N<u>o</u> documento
			</td>
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left">
				Espécie doc.
			</td>
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left">
				Aceite
			</td>
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left">
				Data processamento
			</td>
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left" style="width: 181px;">
				Nosso número
			</td>
		</tr>
		<tr class="small-font">
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left">
				<?php echo $dadosboleto["data_documento"]; ?>
			</td>
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left">
				<?php echo $dadosboleto["numero_documento"]; ?>
			</td>
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left">
				<?php echo $dadosboleto["especie_doc"]; ?>
			</td>
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left">
				<?php echo $dadosboleto["aceite"]; ?>
			</td>
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left">
				<?php echo $dadosboleto["data_processamento"]; ?>
			</td>
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="right">
				<?php echo $dadosboleto["nosso_numero"]; ?>
			</td>
		</tr>
	</tbody>
</table>

<div class="container-row">
	<img alt="" class="thin-solid-line" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/2.png" />
</div>

<table class="container-row" cellpadding="0" cellspacing="0" border="0">
	<tbody>
		<tr class="tiny-font">
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left">
				Uso do banco
			</td>
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left">
				Carteira
			</td>
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left">
				Espécie
			</td>
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left">
				Quantidade
			</td>
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left">
				Valor documento
			</td>
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left" style="width: 181px;">
				(=) Valor documento
			</td>
		</tr>
		<tr class="small-font">
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left">
				
			</td>
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left">
				<?php echo $dadosboleto["carteira"]; ?>
			</td>
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left">
				<?php echo $dadosboleto["especie"]; ?>
			</td>
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left">
				<?php echo $dadosboleto["quantidade"]; ?>
			</td>
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left">
				<?php echo $dadosboleto["valor_unitario"]; ?>
			</td>
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="right">
				<?php echo $dadosboleto["valor_boleto"]; ?>
			</td>
		</tr>
	</tbody>
</table>

<div class="container-row">
	<img alt="" class="thin-solid-line" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/2.png" />
</div>

<table class="container-row" cellpadding="0" cellspacing="0" border="0">
	<tbody>
		<tr class="tiny-font">
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left" style="width: 475px;">
				Instruções (Texto de responsabilidade do cedente)
			</td>
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left" style="width: 182px;">
				(-) Desconto / Abatimentos
			</td>
		</tr>
		<tr class="small-font">
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left">
				
			</td>
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="right">
				
			</td>
		</tr>
	</tbody>
</table>

<table class="container-row" cellpadding="0" cellspacing="0" border="0">
	<tbody>
		<tr class="tiny-font">
			<td valign="top" align="left" style="width: 478px;">
				<table cellpadding="0" cellspacing="0" border="0">
					<tbody>
						<tr class="tiny-font">
							<td valign="top" align="left" style="width: 8px;">
								<img alt="" class="small-vertical-separator" style="height: 108px;" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
							</td>
							<td valign="top" align="left" class="instructions" style="width: 475px;">
								<?php echo $dadosboleto["instrucoes1"]; ?><br />
								<?php echo $dadosboleto["instrucoes2"]; ?><br />
								<?php echo $dadosboleto["instrucoes3"]; ?><br />
								<?php echo $dadosboleto["instrucoes4"]; ?>					
							</td>
							<td valign="top" align="left" style="width: 1px;">
								<img alt="" class="small-vertical-separator" style="height: 108px; margin: 0;" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
							</td>
						</tr>
					</tbody>
				</table>
			</td>
			<td valign="top" align="left" style="width: 188px;">
				<table cellpadding="0" cellspacing="0" border="0" style="width: 100%;">
					<tbody>
						<tr>
							<td style="height: 1px;" colspan="2">
								<img alt="" class="thin-solid-line" style="width: 100%;" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/2.png" />
							</td>
						</tr>
						<tr>
							<td style="width: 7px; height: 26px;">
								
							</td>
							<td valign="top" align="left">
								(-) Outras deduções
							</td>
						</tr>
						<tr>
							<td style="height: 1px;" colspan="2">
								<img alt="" class="thin-solid-line" style="width: 100%;" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/2.png" />
							</td>
						</tr>
						<tr>
							<td style="width: 7px; height: 26px;">
								
							</td>
							<td valign="top" align="left">
								(+) Mora / Multa
							</td>
						</tr>
						<tr>
							<td style="height: 1px;" colspan="2">
								<img alt="" class="thin-solid-line" style="width: 100%;" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/2.png" />
							</td>
						</tr>
						<tr>
							<td style="width: 7px; height: 26px;">
								
							</td>
							<td valign="top" align="left">
								(+) Outros acréscimos
							</td>
						</tr>
						<tr>
							<td style="height: 1px;" colspan="2">
								<img alt="" class="thin-solid-line" style="width: 100%;" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/2.png" />
							</td>
						</tr>
						<tr>
							<td style="width: 7px; height: 26px;">
								
							</td>
							<td valign="top" align="left">
								(=) Valor cobrado
							</td>
						</tr>
					</tbody>
				</table>
			</td>
		</tr>
	</tbody>
</table>

<div class="container-row">
	<img alt="" class="thin-solid-line" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/2.png" />
</div>

<table class="container-row" cellpadding="0" cellspacing="0" border="0">
	<tbody>
		<tr class="tiny-font">
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left" colspan="3">
				Sacado
			</td>
		</tr>
		<tr class="small-font">
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left" colspan="3">
				<?php echo $dadosboleto["sacado"]; ?>
			</td>
		</tr>
		<tr class="small-font">
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left" colspan="3">
				<?php echo $dadosboleto["endereco1"]; ?>
			</td>
		</tr>
		<tr class="small-font">
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td valign="top" align="left" style="width: 475px;">
				<?php echo $dadosboleto["endereco2"]; ?>
			</td>
			<td valign="top" align="left" style="width: 8px;">
				<img alt="" class="small-vertical-separator" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/1.png" />
			</td>
			<td class="tiny-font" valign="top" align="left" style="width: 181px;">
				Cód. baixa
			</td>
		</tr>
	</tbody>
</table>

<div class="container-row">
	<img alt="" class="thin-solid-line" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/2.png" />
</div>

<table class="container-row" cellpadding="0" cellspacing="0" border="0">
	<tbody>
		<tr class="tiny-font">
			<td valign="top" align="left">
				Sacador / Avalista
			</td>
			<td valign="top" align="right">
				<span>Autenticação Mecânica -</span><span class="small-font">Ficha de Compensação</span>
			</td>
		</tr>
		<tr>
			<td rowspan="2">
				<?php fbarcode($dadosboleto["codigo_barras"]); ?>
			</td>
		</tr>
	</tbody>
</table>
<div class="container-row tiny-font" style="text-align: right;">
	Corte na linha pontilhada
</div>
<div class="container-row">
	<img alt="" class="cutting-line" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin/frontend/default/default/images/maxima/bankslip/6.png" />
</div>