<?php

if(!$this->getOrder() || !$this->getSlip())
{
	return;
}
/*
// confere se o usuario estah logado
if(!Mage::helper('customer')->getCustomer()->getId())
{
	return;
}

// confere se o usuario logado eh o usuario da compra
if(Mage::helper('customer')->getCustomer()->getId() != $this->getOrder()->getCustomerId())
{
	return;
}
*/
// define qual bloco importar, de acordo com o banco
echo $this->getChildHtml("Maxima_BankSlip." . $this->getSlip()->getBank());
